[package]
name = "rbrotli-enc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rbrotli-enc-lib = {path = "../lib"}
clap = { version = "4.4.13", features = ["derive"] }
color-eyre = "0.6.2"
